version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: docker/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./sdn:/srv/wsgi_params:z
          - ./log:/var/log/nginx:z
        depends_on:
          - django
    django:
        container_name: wsgi_params
        build: ./oreumi_gg
        image: docker/wsgi_params
        restart: always
        command: uwsgi --ini /srv/wsgi_params/uwsgi.ini
        volumes:
          - ./wsgi_params:/srv/wsgi_params:z
          - ./wsgi_params:/var/log/uwsgi:z