version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: docker/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./sdn:/srv/oreumi_app:z
          - ./log:/var/log/nginx:z
        depends_on:
          - oreumi_app
    oreumi_app:
        container_name: oreumi_app
        build: ./oreumi_app
        image: docker/oreumi_app
        restart: always
        command: uwsgi --ini /srv/oreumi_app/uwsgi.ini
        volumes:
          - ./oreumi_app:/srv/oreumi_app:z
          - ./oreumi_app:/var/log/uwsgi:z