version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: docker/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./sdn:/srv/oreumi_gg:z
          - ./log:/var/log/nginx:z
        depends_on:
          - oreumi_gg
    oreumi_gg:
        container_name: oreumi_gg
        build: ./oreumi_gg
        image: docker/oreumi_gg
        restart: always
        command: uwsgi --ini /srv/oreumi_gg/uwsgi.ini
        volumes:
          - ./oreumi_gg:/srv/oreumi_gg:z
          - ./oreumi_gg:/var/log/uwsgi:z

          
