# Generated by Django 4.2.6 on 2023-10-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(default='admin', max_length=200)),
                ('view', models.IntegerField(default=0)),
                ('category', models.CharField(default='기본', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
            ],
        ),
    ]
