# Generated by Django 4.2.6 on 2023-10-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gg_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
