# Generated by Django 4.2.6 on 2023-10-20 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gg_app", "0002_blogpost_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="image",
        ),
    ]
