# Generated by Django 4.2.6 on 2023-10-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gg_app", "0003_remove_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="comments",
            field=models.ManyToManyField(
                related_name="blog_posts", to="gg_app.comment"
            ),
        ),
    ]
